FROM olbat/debian:testing
MAINTAINER devel@olbat.net

# Install Packages (basic and NodeJS development tools)
RUN apt-get update \
&& apt-get install -y \
  sudo \
  curl \
  nodejs-legacy \
  npm \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

# Add node user and disable sudo password checking
RUN useradd \
  --groups=sudo \
  --create-home \
  --home-dir=/home/node \
  --shell=/bin/bash \
  node \
&& sed -i '/%sudo[[:space:]]/ s/ALL[[:space:]]*$/NOPASSWD:ALL/' /etc/sudoers

# Setup environment
USER node
WORKDIR /home/node

# Default shell
CMD ["/bin/bash","--login","-i"]
